[package]
name = "passwords"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
sha-crypt = { version = "0.5.0", default-features = false }
derive_more = { workspace = true, features = ["display", "from"] }
